### ISSUE TITLE
Your VS Code extension is affected by a security issue and have been blocked

### ISSUE THREAD

**Issue by auchenberg** [hungtin/php-refactor-vscode#1]
Hi,

Kenneth here from the VS Code team. 

Your extension is affected by https://code.visualstudio.com/blogs/2018/11/26/event-stream, and we have blocked your extension.

In order to enable your extension again the workflow is:
  
1) [ ] Fix the extension, submit an update to the marketplace
2) [ ] Send mail to VSMarketplace@microsoft.com and kennau@microsoft.com and notify us.
3) We will verify that the extension is okay
4) Our marketplace will publish the extension again and we'll remove the extension from the blocklist

/k

**Comment by salomalo** [comment]
I am so sorry. This is the only php refactoring extension. it is very **necessary**

**Comment by tinwonda** [comment]
Sorry for the late reply.
I have put a fix for it.
Now it is reviewed by vscode team.

**Comment by auchenberg** [comment]
Your extension has been unblocked. I do apologize for the delay.

**Comment by tinwonda** [comment]
@auchenberg 
https://marketplace.visualstudio.com/items?itemName=tintrinh.php-refactor
I haven't seen it get unblocked. Could you recheck one more time again?
Thank you.
